### ISSUE TITLE
[Message] Thank you for this plug-in!!!!

### ISSUE THREAD

**Issue by FelipeRearden** [nmady/obsidian-multi-line-formatting#1]
Hello @nmady !!!

I just wanna thank you for this plug-in. I have been using for these past days and it help me a lot with my workflow.

Since I use a lot of `tags` to decorate my notes, be able to set hotkeys for each of them really makes me work faster. It's another world for me now.

Thank you very much for this amazing plug-in :)

**Comment by nmady** [comment]
@FelipeRearden, thank you so much for taking the time to write this kind message! I'm so pleased that this plugin is useful to you. I'm curious as to how you use it within your workflow, so if you have time to send a quick screenshot or clip, it would be excellent to see. However, brightening my day with this message was already very generous, so thank you!

**Comment by FelipeRearden** [comment]
Hello again @nmady !!!

Sure, would a be a pleasure. I use html tags to decorate my notes. I love to operate using only the keyboard (makes me work faster). This way I use this amazing plug-in in 3 situations:

### 1- Write inline code 
Hotkey to write inline code `inlinecode` when creating feature requests to be pasted in git.
![Screen Shot 2021-08-14 at 07 53 20](https://user-images.githubusercontent.com/85180696/129444553-9b0fb218-6589-4120-a080-dce933c009c7.png)

### 2- Html Tags + CSS Snippets
I have a bunch of CSS Snippets that changes the behavior of some html tags `<b> <u> <i> <hr> <i> <kbd>` to decorate my notes.
![Screen Shot 2021-08-14 at 08 14 57](https://user-images.githubusercontent.com/85180696/129444574-cb6dd882-4232-4adb-ae9b-48e595d53855.png)

This way I created hotkeys for each one of this tags to make my work faster :)
![Screen Shot 2021-08-14 at 08 17 16](https://user-images.githubusercontent.com/85180696/129444706-18ba1872-d4bb-4a41-b13f-6de041157470.png)


### 3- Markdown Atributtes Plug-in 
There is a new plug-in called [Markdown Attributes](https://github.com/valentine195/obsidian-markdown-attributes) that lets the user create specific changes to lines or paragraphs (without using tags) with this sintax  `{ .class id='id' data=value }`.   

I'm still learning how to use the plug-in, but I created a hotkey to center a paragraph/line 
![Screen Shot 2021-08-14 at 08 04 15](https://user-images.githubusercontent.com/85180696/129444717-3266ab0e-133f-471d-8e41-8fbc82d3e095.png)

---

The sky is the limit. Since I'm always trying to improve my workflow I'm almost sure that I will have more usages for this plug-in. When something new occurs, I will let you know!


Thanks for your kind words too, your words brings joy to my day!

Have a great weekend :)
